<a href="https://colab.research.google.com/github/samhithakalangi/python/blob/main/20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# indexing and slicing 2-dimensional array

In [3]:
import numpy as np

In [5]:
a=np.random.randint(30,99,(7,8))
a

array([[47, 98, 75, 94, 48, 62, 73, 37],
       [39, 61, 49, 81, 68, 38, 39, 51],
       [30, 73, 67, 31, 94, 34, 70, 62],
       [97, 48, 72, 34, 78, 80, 91, 78],
       [56, 64, 47, 36, 98, 51, 73, 90],
       [73, 74, 72, 83, 51, 57, 93, 62],
       [50, 80, 98, 56, 42, 66, 49, 41]])

In [7]:
a.shape

(7, 8)

In [8]:
a.ndim

2

In [10]:
a[0]

array([47, 98, 75, 94, 48, 62, 73, 37])

In [13]:
a[0,7]

37

In [15]:
a[6,0]

50

In [ ]:
# array[row_start:row_end:row_step,col_start:col_end:col_step]

In [16]:
a[2:5]

array([[30, 73, 67, 31, 94, 34, 70, 62],
       [97, 48, 72, 34, 78, 80, 91, 78],
       [56, 64, 47, 36, 98, 51, 73, 90]])

In [17]:
a[2:5,1:4]

array([[73, 67, 31],
       [48, 72, 34],
       [64, 47, 36]])

In [20]:
a[2:5,1:4:2]

array([[73, 31],
       [48, 34],
       [64, 36]])

In [ ]:
# PANDAS = to manipulate the data

In [22]:
import pandas as pd

In [23]:
# 1-dimension pd.Series()
# 2-dimension pd.DataFrame()
# these use to store the data

In [24]:
k=[4,7,2,9,7,3,90,50]
k

[4, 7, 2, 9, 7, 3, 90, 50]

In [25]:
np.array(k)

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [27]:
pd.Series(k)

0     4
1     7
2     2
3     9
4     7
5     3
6    90
7    50
dtype: int64

In [28]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [29]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [30]:
t.shape

(4, 2)

In [31]:
pd.Series(k)

0      [4, 7]
1      [2, 9]
2      [7, 3]
3    [90, 50]
dtype: object

In [36]:
# Series cant accomodate 2-dimensional data
# dataframes can accomodate 2-dimensional data
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [33]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [41]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [39]:
df.columns

Index(['name', 'sub'], dtype='object')

In [50]:
df['sub'].mode()

0     3
1     7
2     9
3    50
Name: sub, dtype: int64

In [42]:
df['sub'].mean()

17.25

In [43]:
df['sub'].median()

8.0

In [44]:
df['sub'].var()

482.9166666666667

In [45]:
df['sub'].std()

21.975364995072702

In [46]:
df['sub'].min()

3

In [47]:
df['sub'].max()

50

In [48]:
df['sub'].quantile(0.25)

6.0

In [49]:
df['sub'].quantile(0.75)

19.25